version: '3'

services:
  tomcat:
    build: .
    ports:
      - "8081:8080"
    volumes:
      # Mount logs directory for easier debugging
      - ./logs:/usr/local/tomcat/logs
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/crudapp
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:14
    ports:
      - "5433:5432"  # Using 5433 to avoid conflict with existing PostgreSQL
    environment:
      - POSTGRES_DB=crudapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d  # To run initial SQL scripts

volumes:
  pg_data: